name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_BUILDKIT: 0  # Disable Buildkit to avoid cache metadata errors

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pre-pull base image  # Optional step to ensure image is available
        run: docker pull kivy/buildozer:latest || true  # Ignore if fails, proceed

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        with:
          workdir: .
          buildozer_version: master
          command: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-package
          path: bin/*.apk